-- Schema creation for H2 Database (Core Financiero)
-- Migración de estructuras PL/SQL a H2

-- Tabla de parámetros del sistema
CREATE TABLE IF NOT EXISTS PFIN_PARAMETRO (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    CVE_MEDIO VARCHAR(20) NOT NULL,
    F_MEDIO DATE,
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, CVE_MEDIO)
);

-- Crear índice único para las foreign keys
CREATE UNIQUE INDEX IF NOT EXISTS IDX_PARAMETRO_EMPRESA ON PFIN_PARAMETRO(CVE_GPO_EMPRESA, CVE_EMPRESA);

-- Tabla de días festivos
CREATE TABLE IF NOT EXISTS PFIN_DIA_FESTIVO (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    CVE_PAIS VARCHAR(5) NOT NULL,
    F_DIA_FESTIVO DATE NOT NULL,
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, CVE_PAIS, F_DIA_FESTIVO)
);

-- Tabla de días de liquidación
CREATE TABLE IF NOT EXISTS PFIN_DIA_LIQUIDACION (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    CVE_LIQUIDACION VARCHAR(10) NOT NULL,
    F_INFORMACION DATE NOT NULL,
    F_LIQUIDACION DATE,
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, CVE_LIQUIDACION, F_INFORMACION)
);

-- Tabla de préstamos
CREATE TABLE IF NOT EXISTS SIM_PRESTAMO (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    ID_PRESTAMO BIGINT NOT NULL,
    CVE_DIVISA VARCHAR(5),
    IMP_PRESTAMO DECIMAL(15,2),
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, ID_PRESTAMO),
    UNIQUE (ID_PRESTAMO)
);

-- Tabla de pre-movimientos
CREATE TABLE IF NOT EXISTS PFIN_PRE_MOVIMIENTO (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    ID_PRE_MOVIMIENTO BIGINT NOT NULL,
    F_OPERACION DATE,
    F_LIQUIDACION DATE,
    F_APLICACION DATE,
    ID_CUENTA BIGINT,
    ID_PRESTAMO BIGINT,
    CVE_DIVISA VARCHAR(5),
    CVE_OPERACION VARCHAR(10),
    IMP_NETO DECIMAL(15,2),
    PREC_OPERACION DECIMAL(10,6) DEFAULT 0,
    TIPO_CAMBIO DECIMAL(10,6) DEFAULT 0,
    CVE_MEDIO VARCHAR(20),
    CVE_MERCADO VARCHAR(20),
    TX_NOTA VARCHAR(500),
    ID_GRUPO BIGINT,
    ID_MOVIMIENTO BIGINT DEFAULT 0,
    CVE_USUARIO VARCHAR(20),
    SIT_PRE_MOVIMIENTO VARCHAR(5) DEFAULT 'NP',
    NUM_PAGO_AMORTIZACION INTEGER,
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, ID_PRE_MOVIMIENTO)
);

-- Tabla de detalle de pre-movimientos
CREATE TABLE IF NOT EXISTS PFIN_PRE_MOVIMIENTO_DET (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    ID_PRE_MOVIMIENTO BIGINT NOT NULL,
    CVE_CONCEPTO VARCHAR(10) NOT NULL,
    IMP_CONCEPTO DECIMAL(15,2),
    TX_NOTA VARCHAR(500),
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, ID_PRE_MOVIMIENTO, CVE_CONCEPTO)
);

-- Índices para optimizar consultas
CREATE INDEX IF NOT EXISTS IDX_DIA_LIQUIDACION_FECHA ON PFIN_DIA_LIQUIDACION(F_INFORMACION, CVE_LIQUIDACION);
CREATE INDEX IF NOT EXISTS IDX_PRE_MOVIMIENTO_FECHA ON PFIN_PRE_MOVIMIENTO(F_OPERACION, F_LIQUIDACION);
CREATE INDEX IF NOT EXISTS IDX_PRE_MOVIMIENTO_SITUACION ON PFIN_PRE_MOVIMIENTO(SIT_PRE_MOVIMIENTO);
CREATE INDEX IF NOT EXISTS IDX_DIA_FESTIVO_FECHA ON PFIN_DIA_FESTIVO(F_DIA_FESTIVO);
CREATE INDEX IF NOT EXISTS IDX_PRESTAMO_ID ON SIM_PRESTAMO(ID_PRESTAMO);
CREATE INDEX IF NOT EXISTS IDX_PRE_MOVIMIENTO_PRESTAMO ON PFIN_PRE_MOVIMIENTO(ID_PRESTAMO);
CREATE INDEX IF NOT EXISTS IDX_PRE_MOVIMIENTO_MERCADO ON PFIN_PRE_MOVIMIENTO(CVE_MERCADO);

-- Agregar foreign keys después de crear todas las tablas
ALTER TABLE PFIN_DIA_FESTIVO ADD CONSTRAINT FK_DIA_FESTIVO_EMPRESA 
    FOREIGN KEY (CVE_GPO_EMPRESA, CVE_EMPRESA) REFERENCES PFIN_PARAMETRO(CVE_GPO_EMPRESA, CVE_EMPRESA);

ALTER TABLE PFIN_DIA_LIQUIDACION ADD CONSTRAINT FK_DIA_LIQUIDACION_EMPRESA 
    FOREIGN KEY (CVE_GPO_EMPRESA, CVE_EMPRESA) REFERENCES PFIN_PARAMETRO(CVE_GPO_EMPRESA, CVE_EMPRESA);

ALTER TABLE SIM_PRESTAMO ADD CONSTRAINT FK_PRESTAMO_EMPRESA 
    FOREIGN KEY (CVE_GPO_EMPRESA, CVE_EMPRESA) REFERENCES PFIN_PARAMETRO(CVE_GPO_EMPRESA, CVE_EMPRESA);

ALTER TABLE PFIN_PRE_MOVIMIENTO ADD CONSTRAINT FK_PRE_MOVIMIENTO_PRESTAMO 
    FOREIGN KEY (ID_PRESTAMO) REFERENCES SIM_PRESTAMO(ID_PRESTAMO);

ALTER TABLE PFIN_PRE_MOVIMIENTO_DET ADD CONSTRAINT FK_PRE_MOVIMIENTO_DET_CABECERA 
    FOREIGN KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, ID_PRE_MOVIMIENTO) 
    REFERENCES PFIN_PRE_MOVIMIENTO(CVE_GPO_EMPRESA, CVE_EMPRESA, ID_PRE_MOVIMIENTO) ON DELETE CASCADE;

-- Tabla de catálogo de operaciones
CREATE TABLE IF NOT EXISTS PFIN_CAT_OPERACION (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    CVE_OPERACION VARCHAR(10) NOT NULL,
    TX_DESCRIPCION VARCHAR(100),
    CVE_AFECTA_SALDO VARCHAR(1) NOT NULL CHECK (CVE_AFECTA_SALDO IN ('I', 'D', 'N')),
    ST_ESTATUS VARCHAR(1) DEFAULT 'A' CHECK (ST_ESTATUS IN ('A', 'S')),
    TX_OBSERVACIONES VARCHAR(200),
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, CVE_OPERACION)
);

-- Tabla de movimientos procesados
CREATE TABLE IF NOT EXISTS PFIN_MOVIMIENTO (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    ID_MOVIMIENTO BIGINT NOT NULL,
    ID_CUENTA BIGINT,
    CVE_DIVISA VARCHAR(5),
    F_OPERACION DATE,
    F_LIQUIDACION DATE,
    F_APLICACION DATE,
    CVE_OPERACION VARCHAR(10),
    IMP_NETO DECIMAL(15,2),
    PREC_OPERACION DECIMAL(10,6) DEFAULT 0,
    TIPO_CAMBIO DECIMAL(10,6) DEFAULT 0,
    ID_REFERENCIA BIGINT,
    ID_PRESTAMO BIGINT,
    CVE_MERCADO VARCHAR(20),
    CVE_MEDIO VARCHAR(20),
    TX_NOTA VARCHAR(500),
    TX_REFERENCIA VARCHAR(100),
    ID_GRUPO BIGINT,
    ID_PRE_MOVIMIENTO BIGINT,
    SIT_MOVIMIENTO VARCHAR(5) NOT NULL,
    FH_REGISTRO TIMESTAMP,
    FH_ACTIVACION TIMESTAMP,
    LOG_IP_ADDRESS VARCHAR(45),
    LOG_OS_USER VARCHAR(100),
    LOG_HOST VARCHAR(100),
    CVE_USUARIO VARCHAR(20),
    CVE_USUARIO_CANCELA VARCHAR(20),
    NUM_PAGO_AMORTIZACION INTEGER,
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, ID_MOVIMIENTO)
);

-- Tabla de detalle de movimientos
CREATE TABLE IF NOT EXISTS PFIN_MOVIMIENTO_DET (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    ID_MOVIMIENTO BIGINT NOT NULL,
    CVE_CONCEPTO VARCHAR(10) NOT NULL,
    IMP_CONCEPTO DECIMAL(15,2),
    TX_NOTA VARCHAR(500),
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, ID_MOVIMIENTO, CVE_CONCEPTO)
);

-- Tabla de saldos por cuenta/fecha/divisa
CREATE TABLE IF NOT EXISTS PFIN_SALDO (
    CVE_GPO_EMPRESA VARCHAR(10) NOT NULL,
    CVE_EMPRESA VARCHAR(10) NOT NULL,
    F_FOTO DATE NOT NULL,
    ID_CUENTA BIGINT NOT NULL,
    CVE_DIVISA VARCHAR(5) NOT NULL,
    SDO_EFECTIVO DECIMAL(15,2) DEFAULT 0,
    PRIMARY KEY (CVE_GPO_EMPRESA, CVE_EMPRESA, F_FOTO, ID_CUENTA, CVE_DIVISA)
);

-- Secuencia para IDs de movimientos
CREATE SEQUENCE IF NOT EXISTS SQ01_PFIN_MOVIMIENTO START WITH 1 INCREMENT BY 1;

-- Comentarios en las tablas
COMMENT ON TABLE PFIN_PARAMETRO IS 'Parámetros del sistema financiero';
COMMENT ON TABLE PFIN_DIA_FESTIVO IS 'Días festivos por país y empresa';
COMMENT ON TABLE PFIN_DIA_LIQUIDACION IS 'Fechas de liquidación para operaciones financieras';
COMMENT ON TABLE SIM_PRESTAMO IS 'Información de préstamos';
COMMENT ON TABLE PFIN_PRE_MOVIMIENTO IS 'Pre-movimientos de tesorería';
COMMENT ON TABLE PFIN_PRE_MOVIMIENTO_DET IS 'Detalle de conceptos de pre-movimientos';
COMMENT ON TABLE PFIN_CAT_OPERACION IS 'Catálogo de operaciones financieras';
COMMENT ON TABLE PFIN_MOVIMIENTO IS 'Movimientos financieros procesados';
COMMENT ON TABLE PFIN_MOVIMIENTO_DET IS 'Detalle de conceptos de movimientos';
COMMENT ON TABLE PFIN_SALDO IS 'Saldos de cuentas por fecha y divisa';